language: python
sudo: false
matrix:
  include:
    - python: 3.7
      env: TOXENV=py3flake8
      dist: xenial
      sudo: true
    - python: 2.7
      env: TOXENV=py2flake8
      dist: trusty
      sudo: false
    - python: 3.6
      env: TOXENV=doc
      dist: trusty
      sudo: false
    - python: pypy3
      env: TOXENV=pypy3
      dist: trusty
      sudo: false
    - python: pypy
      env: TOXENV=pypy
      dist: trusty
      sudo: false
    - python: 3.5
      env: TOXENV=py35
      dist: trusty
      sudo: false
    - python: 3.6
      env: TOXENV=py36
      dist: trusty
      sudo: false
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: 3.9
      env: TOXENV=py39
      dist: xenial
      sudo: true
    - python: 2.7
      env: TOXENV=py27
      dist: trusty
      sudo: false

install:
  - travis_retry pip install tox

script:
  - tox

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
  user: twiggy-uploader
  password:
    secure: C5xa94mGVqCk1Ti7TEQe8j6b/ZSlQOGeQ5iXMxJgunXPtpBVxPIbK9AkG1rLxqXJXy2EIP1tqwovvO03/iynrNphPTDRlNkVYFUHQhxvHUygtnZ9CRispNfjMKIu4nrgRiWQLFtllYrdyrsKv+WD4yO1hVHUOlPq85x6QaXmC1k=
